title: yourstitle
description: add some description for your website
author: whoami
favicon: /favicon.ico
about: "What i'm doing?"
contact_mail: whoami
contact_mail_at: "[at]..."
google_analytics: 


avatar_url: /static/img/avatar.png
path_logo:

github_url:

baseurl: ""
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
